### ISSUE TITLE
enhanced postform

### ISSUE THREAD

**Issue by KDeluxe2023** [KDeluxe2023/KDeluxe2023#19]
widzę, że od jakiegoś czasu są problemy z tym modułem, nie działa saga i nie da się wpisać wordfiltra. w konsoli nie ma żadnych błędów, trzeba to zbadać

**Comment by smieclubiacywdupala** [comment]
ctrl+enter nie działa

**Comment by KDeluxe2023** [comment]
> ctrl+enter nie działa

ten moduł jest cały rozjebany odkąd go przepisałem na vanilla js, trzeba nad nim usiąść całościowo. spróbuje do następnego update to zrobić na razie polecam to wyłączyć

**Comment by KDeluxe2023** [comment]
naprawiono
