### ISSUE TITLE
enhanced postform: ctrl+enter

### ISSUE THREAD

**Issue by KDeluxe2023** [KDeluxe2023/KDeluxe2023#23]
wciśnięcie ctrl+enter w obrębie textboxa w formularzu wysyłania posta powoduje też niechciane zachowanie: oprócz wysłania posta, uruchamia też funkcję popout

**Comment by smieclubiacywdupala** [comment]
wydaje mi się że nawet przyczepiony odczepia a odczepiony przyczepia

**Comment by KDeluxe2023** [comment]
> wydaje mi się że nawet przyczepiony odczepia a odczepiony przyczepia

nie rozumiem ale naprawie to niedługo może dzisiaj

**Comment by smieclubiacywdupala** [comment]
webmrel https://imgur.com/qwXACMV

**Comment by smieclubiacywdupala** [comment]
a kliknięcie w odpisz nie powoduje odpięcia popupa webmrel https://imgur.com/FMqa9XY

**Comment by KDeluxe2023** [comment]
> a kliknięcie w odpisz nie powoduje odpięcia popupa webmrel https://imgur.com/FMqa9XY

to akurat nigdy nie był ficzer, a powinno tak być? moge to dodać jako opcje w ustawieniach

**Comment by smieclubiacywdupala** [comment]
no skoro popout ma opcje >przyczep i >odczep to uważam że to właśnie one powinny do tego służyć a ctrl+enter do wysłania tosta tylko

**Comment by KDeluxe2023** [comment]
> no skoro popout ma opcje >przyczep i >odczep to uważam że to właśnie one powinny do tego służyć a ctrl+enter do wysłania tosta tylko

nie no to jest jasne ale napisałeś, że wysłanie posta docelowo powinno też odczepiać chyba że źle zrozumiałem

**Comment by smieclubiacywdupala** [comment]
musisz to chyba jakoś z fast reply powiązać bo kdeluxe wyłącza fast reply
i też jest tak że okienko od fast reply pojawia sie na poziomie posta który sie >>cytuje a w ehanced postform to trzeba najpierw przypierdolić we fredzie pustego ctrl+enter żeby to działało jak orginalne fast reply

ogólnie wydaje mi się że całość jest zjebana ale  i tak szanuje że ci sie chce xD

**Comment by KDeluxe2023** [comment]
> musisz to chyba jakoś z fast reply powiązać bo kdeluxe wyłącza fast reply i też jest tak że okienko od fast reply pojawia sie na poziomie posta który sie >>cytuje a w ehanced postform to trzeba najpierw przypierdolić we fredzie pustego ctrl+enter żeby to działało jak orginalne fast reply
> 
> ogólnie wydaje mi się że całość jest zjebana ale i tak szanuje że ci sie chce xD

taki był zamysł, że to jest zamiast fast reply, funkcja full compatibility blokuje włączanie fast reply. mitsuba ma problem z fastreply w większych fredach, one po prostu nie działa. zmieniam to teraz i popout będzie jako dodatkowa opcja

**Comment by KDeluxe2023** [comment]
funkcja popout została przeniesiona do własnej "sub-opcji" tak więc można wyłączyć popout nie wyłączając enhanced postform. bonusowo dodano sub-opcje, która pozwala odpiąć wszystkie przechwycenia klawiszy w obrębie formularza - może być przydatne w niektórych ustawieniach systemowych/klawiaturach do wpisywania znaków diaktrycznych
