### ISSUE TITLE
blind mode tts: nie działa, błąd krytyczny

### ISSUE THREAD

**Issue by BiscuitKrueger** [KDeluxe2023/KDeluxe2023#24]
Przeglądarka: Chrome
Wersja przeglądarki: 98.0.4758.102 (najnowsza)
Wtyczka do userjs: Tampermonkey
Dokładne kroki pozwalające zreprodukować problem: korek analny w dupie
1. zainstaluj rozszerzenie Tampermonkey na przeglądarce Chrome o wersji 98.0.4758.102 z oficjalnego upstream'u
2. zainstaluj userscripta
3. wejdź na kabaczka
Zrzut ekranu z konsoli (F12):
![log z konsoli](https://user-images.githubusercontent.com/108426474/209715254-c033592d-30bd-429d-aa2f-1cfab5fbd492.png)

**Comment by KDeluxe2023** [comment]
to już jest od dawna, co sie zjebało po aktualizacji tego API responsivevoice ale jak patrzyłem do dokumentacji to wygląda ok więc huj wie o co chodzi z tą redeklaracją. tak poza tym to moduł TTS pisał jakiś inny anon. spojrze na to przy następnej aktualizacji

**Comment by KDeluxe2023** [comment]
połączono https://github.com/KDeluxe2023/KDeluxe2023/issues/35
