### ISSUE TITLE
wyłączenie obserwowania fredów wysrywa liste obserwowanych

### ISSUE THREAD

**Issue by smieclubiacywdupala** [KDeluxe2023/KDeluxe2023#25]
W sensie nie dodają się nowe fredy nawet jak się kliknie w [Obserwuj]

**Comment by KDeluxe2023** [comment]
dzisiaj to sprawdze i naprawie

**Comment by KDeluxe2023** [comment]
> W sensie nie dodają się nowe fredy nawet jak się kliknie w [Obserwuj]

nie jestem w stanie zreplikować tego błędu, napisz zgłoszenie zgodne z [formatem](https://github.com/KDeluxe2023/KDeluxe2023/issues/2)

**Comment by smieclubiacywdupala** [comment]
sage sam w siebie chodzi chyba o #22
