### ISSUE TITLE
enhancement: dodanie nieoficjalnych a fajnych CSSów do dropdown listy styli

### ISSUE THREAD

**Issue by BiscuitKrueger** [KDeluxe2023/KDeluxe2023#31]
https://pastebin.com/TJ7t2DrT - windows 95
https://pastebin.com/Us0nPafa - shogun
https://pastebin.com/xqdWmZmY - orgonicki
https://pastebin.com/i4zT4pMd - wykopowy
https://pastebin.com/7ykYUtkc - blackroach
https://pastebin.com/Up5juydn - karagen
https://userstyles.org/styles/213577/modernroach - modernroach

**Comment by KDeluxe2023** [comment]
zrobie to dzisiaj w nocy

**Comment by KDeluxe2023** [comment]
dodano w [0.8.2](https://github.com/KDeluxe2023/KDeluxe2023/releases/tag/0.8.2-beta)
